spring.application.name=tutorial_spring_boot
server.port=8081
config.code = 11112
config.username = jonas
config.message = Hola que tal como esta
config.listOfValues = hola,que,tal,estas 
config.valuesMap = {product: 'Intel Core', description: 'Bueno Bonito y Barato',precio:'999'} 

